import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Layout } from './components/Layout/Layout';
import favicon from '/favicon.ico'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NinoMedTech',
  
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      
      <body id='body' className={inter.className}>
      <Layout>
        {children}
      </Layout>
        </body>
    </html>
  )
}
