import type { Metadata } from 'next'
import style from './catalog.module.css'
import Link from 'next/link'
import { Container } from '../components/Container/Container'

export const metadata: Metadata = {
  title: 'NinoMedTech',
  description: 'Generated by create next app',
}

export default async function CatalogLayout({ children}:{children: React.ReactNode}) {
  
  return (

        <section>
          <Container>
            {children}
          </Container>
        </section>
  )
      
}